export const ADD_INCIDENTS = 'ADD_INCIDENTS';
export const INCIDENTS_FAILED = 'INCIDENTS_FAILED';
export const INCIDENTS_LOADING = 'INCIDENTS_LOADING';
export const CREATE_INCIDENT = 'CREATE_INCIDENT';
export const UPDATE_INCIDENT = 'UPDATE_INCIDENT'; 
